# .github/workflows/build-aab.yml
name: Android • Build AAB (Capacitor)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - uses: android-actions/setup-android@v2   # installs cmdline-tools + SDK

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Add Capacitor Android dependency
        # append the line only if it's not already in build.gradle
        run: |
          grep -q "com.getcapacitor:capacitor-android" android/app/build.gradle || \
          sed -i '/dependencies {/a \    implementation "com.getcapacitor:capacitor-android:5.0.6"' \
            android/app/build.gradle

      - name: Build release bundle
        working-directory: android
        run: ./gradlew --no-daemon --stacktrace bundleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
